import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: {
    template: "Custom Hooks Examples | %s",
    default: "Custom Hooks Examples | Home",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <section>
          {/* Include shared UI here e.g. a header or sidebar */}
          <nav className="row-start-3 flex gap-6 flex-wrap items-center justify-center mt-3">
            <Link
              href="/"
              className="flex items-center gap-2 border-double border-b-4 border-orange-300 focus:border-white"
            >
              Home
            </Link>
            <Link
              href="/counter"
              className="flex items-center gap-2 border-double border-b-4 border-orange-300 focus:border-white"
            >
              Counter
            </Link>
            <Link
              href="/fetcher"
              className="flex items-center gap-2 border-double border-b-4 border-orange-300 focus:border-white"
            >
              Fetcher
            </Link>
            <Link
              href="/debouncer"
              className="flex items-center gap-2 border-double border-b-4 border-orange-300 focus:border-white"
            >
              Debouncer
            </Link>
          </nav>
        </section>
        {children}
      </body>
    </html>
  );
}
